# ─────────────────────────────────────────────────────────────────────────────
# Dockerfile.airflow
# Extends the official Airflow image with project-specific Python packages
# ─────────────────────────────────────────────────────────────────────────────
FROM apache/airflow:2.10.5

USER airflow

RUN pip install --no-cache-dir \
    kafka-python-ng \
    "pymongo==4.6.1" \
    "requests==2.31.0" \
    "python-dotenv==1.0.0" \
    "pandas==3.0.2" \
    "numpy==2.4.4"
